[settings]
not_found_auto_install = false
paranoid = true
pin = true
trusted_config_paths = ['~/.config/mise/config.toml']
idiomatic_version_file_enable_tools = []

[settings.status]
missing_tools = "always"
show_env = true

[settings.pipx]
uvx = true

[settings.npm]
package_manager = "pnpm"

[tools]
cargo-binstall = "1.17.8"
deno = "2.7.7"
pnpm = "10.33.0"
usage = "3.2.0"
uv = "0.11.1"
